### ISSUE TITLE
Configuration for Basic Authentication ( prometheus/alertmanager)

### ISSUE THREAD

**Issue by Dkarag** [prometheus-community/helm-charts#1186]
I have deployed kube-prometheus-stack using helm charts. The version I use is  15.1.3 .
Everything works as expected.  Now I want to enable the Basic Auth feature.
According to the official documentation, this is supported and can be enabled using the following attribute

$ prometheus -web.config.file=web.yml

Can I use this feature with kube-prometheus-stack? I want to secure the endpoints (prometheus/alertmanager).

Has anyone achieved it with the approach of using web.config.file?

**Comment by thirdeyenick** [comment]
I would like to enable basic auth as well. Looking at the [corresponding section](https://github.com/prometheus-operator/prometheus-operator/blob/f103831b389be5cf504bdf28002cfa2915b821ed/pkg/apis/monitoring/v1/types.go#L516) of the Prometheus Operator "Prometheus" CRD, it seems you can only specify the page title and TLS options, but not basic auth.

So I'd say basic auth would need to be handled via ingress features (like with [nginx ingress](https://kubernetes.github.io/ingress-nginx/examples/auth/basic/)). Would be cool if the helm chart would support this somehow (including the creation of the corresponding secret).

**Comment by prab2014** [comment]
> > is this done in prometheus/promethues chart too? i need to add basic auth using helm chart. not sure where to specify the value in the yaml.
> > #1255
> 
> take a look at this values.yaml file https://github.com/ninech/helm-charts/blob/645fe6000cd2baf0fb8d0a439b1d3636f6e2dd36/charts/kube-prometheus-stack/values.yaml#L1782

I am using prometheus chart not the kube one.. enabling basic auth is creating issue in pod liveness,

**Comment by brsolomon-deloitte** [comment]
> So I'd say basic auth would need to be handled via ingress features (like with nginx ingress).

Disagree with the "need to be" part of this statement. It clearly doesn't _need_ to be done that way since the `prometheus` chart from this repository allows you to configure `basic_auth_users` in Prometheus server web.config.yml:

https://github.com/prometheus-community/helm-charts/issues/1255#issuecomment-983635542

The difficulty from admin perspective is that `prometheus` and `kube-prometheus-stack` now differ starkly in how (and to what extent) they support basic auth in Prometheus.
