### ISSUE TITLE
Host root file system mounting and security

### ISSUE THREAD

**Issue by huornlmj** [prometheus-community/helm-charts#1388]
https://github.com/prometheus-community/helm-charts/blob/2cacc16807caedc6cabf1606db27e0d78c844564/charts/prometheus-node-exporter/templates/daemonset.yaml#L159

From a security standpoint, mounting a hosts full root / directory into a container is a high risk practice and not aligned with the principle of least privilege.   It also negates any other specific mount points.  Why is the host's full root / mounted for Prometheus?  instead, why aren't only the directories required mounted instead?  For example, why would Prometheus need access to /var/run/docker.sock?  You should never see that mounted into a container, but it's happening here for some reason.

**Comment by kfox1111** [comment]
Its protected by an if, but its defaulted on:
hostRootFsMount: true

+1 for seeing if there is a better default with finer grained permissions.

**Comment by ww3pl** [comment]
Not sure if this is of any consolation, but it seems kube-prometheus [has the very same default, without the if switch it seems](https://github.com/prometheus-operator/kube-prometheus/blob/d0464b2bde9c0ce581b7fdf541baa23700529e15/jsonnet/kube-prometheus/components/node-exporter.libsonnet#L245).

I do agree that if this mount is not needed it absolutely shouldn't be there.

**Comment by huornlmj** [comment]
Touching the issue as it is a severe overreach in volume mounting.

**Comment by ww3pl** [comment]
@huornlmj 
I've just checked out the Prometheus repository for the Node Exporter ( https://github.com/prometheus/node_exporter )

If you take a look at the readme, you'll see that the whole idea of mounting the whole root path came not from here, not from kube-prometheus, but from Node Exporter repo itself. 

Therefore I think if there's any enhancement to be made, it should sadly start over there.

**Comment by huornlmj** [comment]
Thanks @ww3pl.  I will see if I can get attention to the issue there.

**Comment by huornlmj** [comment]
I've raised the issue back at Prometheus but I re-read their README.  They clearly state that Prometheus should not be run in a Docker container, specifically for the reason I've raised here.  (https://github.com/prometheus/node_exporter#docker).  While they advise against it, they offer advise to mount the host file system if you do wish to containerize.  I think this advise is where the issue stems from.  I've asked them to reconsider this, but it does look like the overall guidance is being over looked for this helm chart.  So it might be down to this community to apply a granular control to provide a secure container deployment

**Comment by Boojapho** [comment]
Did some digging in the node exporter repo.  There are three main path points that collectors use: `/`, `/proc`, and `/sys`.  You can pass in the location of these items through `--path.rootfs`, `--path.procfs`, and `--path.sysfs`.  Since most of the collectors use `/proc` and `/sys`, those become two mounts we need. 

I searched through the code for `rootfs` and found that only the `filesystem` and `os_release` collectors actually use this variable.  `os_release` looks at `/etc/os-release` and `/usr/lib/os-release`.  The `filesystem` collector uses a system call to `statfs()` to get disk usage on all the mount points.  This uses `/`.

I also noticed a couple collectors use directories from options.  But I don't b
- The `textfile` collector gets an arbitrary directory from `--collector.textfile.directory` to check files anywhere.
- The `runit` collector gets an arbitrary directory from `--collector.runit.servicdir` to find its service files.
Neither of these are on by default

If we want to make the Helm chart not use `/`, we will have to 
1. Mount `/etc/os-release` and `/usr/lib/os-release` into `/host/root`
2. Upstream in node-exporter, modify the `filesystem` collector to remove dependency on the root filesystem.
