### ISSUE TITLE
[kube-prometheus-stack] Prometheus Operator pod cannot come up when admission hook is disabled

### ISSUE THREAD

**Issue by AndrewSav** [prometheus-community/helm-charts#1438]
### Describe the bug a clear and concise description of what the bug is.

Prometheus Operator pod cannot come up with a missing admission hook secret error if admission hook is disabled.

### What's your helm version?

v3.7.0

### What's your kubectl version?

v1.22.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

19.0.2

### What happened?

The operator pod cannot come up, with the following error message: `MountVolume.SetUp failed for volume "tls-secret" : secret "prometheus-kube-prometheus-admission" not found`. This message is displayed because admission hook is disabled and the secret is not present.

### What you expected to happen?

I expect the operator to come up.

### How to reproduce it?

Install the chart with the values below

### Enter the changed values of values.yaml?

```yaml
prometheusOperator:
  admissionWebhooks:
    enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f prometheus-values.yaml

**Comment by AndrewSav** [comment]
+1

**Comment by AndrewSav** [comment]
+1

**Comment by monotek** [comment]
Works for me.

**Comment by AndrewSav** [comment]
@monotek do you have the `prometheus-kube-prometheus-admission` secret?

**Comment by gw0** [comment]
Same issue with `kube-prometheus-stack` 31.0.0 on a fresh cluster. I disabled the admission webhooks, because I do not configure Prometheus in this way and there is no need for it to be running.
```yaml
prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: false
```

While looking at the code it seems conceptually wrong that the `prometheus-operator` uses the same TLS certificates intended to be used by the admission webhooks. It should generate it's own certificates if needed or there should be instructions on how to set it up.
- https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L126

Workaround 1: Disable TLS (traffic to operator is now unencrypted?):
```yaml
  tls:
    enabled: false
```

Workaround 2: Enable the generation of admission webhooks certificates with cert-manager despite it being disabled (generated by [certmanager.yaml#L42](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/certmanager.yaml#L42)):
```yaml
  admissionWebhooks:
    enabled: false
    certManager:
      enabled: true
```

Workaround 3: Manually create the needed TLS secrets/certificates.

**Comment by obvionaoe** [comment]
+1

**Comment by AndrewSav** [comment]
recent activity

**Comment by danmanners** [comment]
More recent activity

**Comment by AndrewSav** [comment]
Even more recent activity

**Comment by AndrewSav** [comment]
Hello there

**Comment by ravindraprasad85** [comment]
Can anyone please fix and share the resolution? i have deployed in my environment and not able to see **prometheus-kube-prometheus-stack-prometheus-0** pod

**Comment by jkleinkauff** [comment]
I'm facing the same issue.

**Comment by AndrewSav** [comment]
remove stale

**Comment by AndrewSav** [comment]
Re-opened as <https://github.com/prometheus-community/helm-charts/issues/2742> since it was closed by the bot.

**Comment by nicl-dev** [comment]
Any news on this issue? It's still closed but I just encountered this problem.
