### ISSUE TITLE
[prometheus-kube-stack] Wrong Prometheus-Operator image default value in values.yaml

### ISSUE THREAD

**Issue by kharf** [prometheus-community/helm-charts#1480]
### Describe the bug a clear and concise description of what the bug is.

There is a default value for the prometheus operator image in the values.yaml: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1632
This states that I can override the operator image via:
```
values:
  image:
    tag: v0.51.2
```
This overrides nothing though, as the deployment template expects another hierarchy, like:
```
values:
  prometheusOperator:
    image:
      tag: v0.51.2
```
see: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L36

Same applies to prometheusConfigReloaderImage

### What's your helm version?

v3.7.1

### What's your kubectl version?

v1.22.3

### Which chart?

prometheus-kube-stack

### What's the chart version?

19.2.2

### Enter the command that you execute and failing/misfunctioning.

helm upgrade [RELEASE_NAME] prometheus-community/kube-prometheus-stack --version 19.2.2

this is not failing though, since it just overrides nothing

**Comment by mac-chaffee** [comment]
Is there a chance you're missing the two spaces at the start of the line? https://github.com/prometheus-community/helm-charts/blob/6630cee03709c2ee6e44b26ef7bdd9c3bcbd92e2/charts/kube-prometheus-stack/values.yaml#L1632

The values.yaml appears correct to me since the `prometheusOperator:` part is there, just on line 1398: https://github.com/prometheus-community/helm-charts/blob/6630cee03709c2ee6e44b26ef7bdd9c3bcbd92e2/charts/kube-prometheus-stack/values.yaml#L1398-L1632

So to override it, your values.yaml file needs to be:

```
prometheusOperator:
  image:
    tag: <version>
```
then run `helm upgrade [RELEASE_NAME] prometheus-community/kube-prometheus-stack --version 19.2.2 -f values.yaml`

**Comment by kharf** [comment]
hey @mac-chaffee, you are right. Somehow I tought it was in the same hierarchy. Sry, I close that
