### ISSUE TITLE
[prometheus] How to change storage.tsdb.retention.size?

### ISSUE THREAD

**Issue by MikeMichel** [prometheus-community/helm-charts#1701]
Using 

```
  extraArgs:
    - storage.tsdb.retention.size:7GB
```
results in:
```
  - args:
....
    - --0=storage.tsdb.retention.size:7GB
 ```

and using
```
  extraFlags:
    - storage.tsdb.retention.size:7GB
```

results in
```
  - args:
....
    - --map[storage.tsdb.retention.size:7GB]
```

How to do it the right way as both produce an error on startup?

### What's your helm version?

v3.7.1

### What's your kubectl version?

1.19.10

### Which chart?

prometheus

### What's the chart version?

15.0.2

### Enter the command that you execute and failing/misfunctioning.

helm --version=15.0.2 upgrade -i --reset-values --wait --timeout 300s --atomic --create-namespace -f=/tmp/tmpg08s832t.yml prometheus prometheus/prometheus

**Comment by shinebayar-g** [comment]
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2289

![image](https://user-images.githubusercontent.com/3091558/148982267-e2a67d81-c4f6-4cc3-aa87-42fa92544927.png)

**Comment by MikeMichel** [comment]
this option does not exist for the "prometheus" stack.

**Comment by shinebayar-g** [comment]
Try

```yml
server:
  extraArgs:
    storage.tsdb.retention.size: 7GB
```

**Comment by MikeMichel** [comment]
This gives me
```
Error parsing commandline arguments: unknown long flag '--storage\.tsdb\.retention\.size'
prometheus: error: unknown long flag '--storage\.tsdb\.retention\.size'
```
Deploying with ansible helm module.

**Comment by monotek** [comment]
```
helm template . --set server.extraFlags[0]=storage.tsdb.retention.size=7GB
```

**Comment by raykrueger** [comment]
I ran into the `Error parsing commandline arguments: unknown long flag '--storage\.tsdb\.retention\.size'` as well.
Turns out I was putting the extraArgs in alertmanager, not server, as it is the first extraArgs value in the template.

Future readers, be sure you are putting it in server.extraArgs, not alertmanager.extraArgs. Thee following format works fine...

```yaml
extraArgs:
    'storage.tsdb.retention.size': 5GB
```

**Comment by chromatices** [comment]
In my case, i edited crd named 'prometheus.monitoring.coreos.com' - 'default'. That crd has option about retention, and it has default value ('15d'). So that i edited that, check with `kubectl describe pod <prometheus pod name> | grep retention`.

![image](https://user-images.githubusercontent.com/56014940/164391657-c2ba088e-64f6-4424-9927-64413d3d8e10.png)

**Comment by ivel13** [comment]
The command which worked for me:
`helm upgrade --install prometheus prometheus-community/prometheus --set server.extraFlags[0]=storage.tsdb.retention.size=10GB`

**Comment by Jose-Matsuda** [comment]
I ran into something similar trying to make use of `extraArgs` with the `--data.retention` option running into the 
`- --0=storage.tsdb.retention.size:7GB` bit

Turns out I just misinterpreted the format, it should just be like the following
![image](https://user-images.githubusercontent.com/23174198/212339712-024a669c-317e-4595-bd22-11e373736d35.png)
