### ISSUE TITLE
[kube-prometheus-stack] Make sure that chart is tested before release, if install fails do not release 

### ISSUE THREAD

**Issue by samip5** [prometheus-community/helm-charts#1800]
### Is your feature request related to a problem ?

I'm very frustrated with how many times the chart is updated and it breaks entirely.

### Describe the solution you'd like.

I would like the chart testing to be expanded to test it before release, and if it has any errors, it doesn't get released until those are fixed.

### Describe alternatives you've considered.

N/A

### Additional context.
Example:
```
kube-prometheus-stack   False   Helm install failed: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Endpoints.subsets[0].ports[0]): missing required field "port" in io.k8s.api.core.v1.EndpointPort   6s
```

**Comment by samip5** [comment]
> All charts are tested and installed into a kind cluster before released. Thats done in the pr itself.
> 
> Example for the last kube-proemethus-stack pr: https://github.com/prometheus-community/helm-charts/runs/5131050958?check_suite_focus=true

So despite that, how did this happen? https://github.com/prometheus-community/helm-charts/issues/1801

**Comment by samip5** [comment]
I think the testing should be done in master, after the PR is merged to mitigate that.

**Comment by monotek** [comment]
> So despite that, how did this happen? #1801

likely some custom config which differs from the defaults.

> I think the testing should be done in master, after the PR is merged to mitigate that.

That makes no sense at all as the release happens if a pr is merged to master.
That would mean testing is done after the release.

**Comment by Zebradil** [comment]
It is not reproducible with the default values, because some templates aren't rendered in this case. In #2162 I show an example of when it happens.

In my opinion, default values can't be relied on during testing, because they serve another purpose. Proper testing can be done via unit tests (as it is done for Alertmanager [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/unittests/alertmanager)), but that might require a lot of work.
