### ISSUE TITLE
slack_api_url_file and alertmanager secrets not mounted

### ISSUE THREAD

**Issue by bovy89** [prometheus-community/helm-charts#1864]
I'm trying to configure alertmanager-slack integration.

I want to use `slack_api_url_file` parameter and a k8s secret in order to avoid to put the entire `alertmanager.yaml` file in a secret.

values file:

```
    alertmanagerSpec:
      secrets:
        - slack-pass
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname', 'job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 24h
        receiver: 'slack'
        routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
      receivers:
      - name: 'null'
      - name: 'slack'
        slack_configs:
        - channel: '#k8s_dev'
          slack_api_url_file: /etc/alertmanager/secrets/<TODO>
          send_resolved: true
      inhibit_rules:
      - source_matchers: [severity="critical"]
        target_matchers: [severity="warning"]
        equal: ['alertname', 'job']
      templates:
      - '/etc/alertmanager/config/*.tmpl'
 ```

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
     .....
  creationTimestamp: "2021-10-01T09:25:50Z"
  generation: 3
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 32.2.0
    chart: kube-prometheus-stack-32.2.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-alertmanager
  namespace: monitoring
  resourceVersion: "81458543"
  uid: 1b8878cb-7312-49ae-928d-a5d98d3eb98c
spec:
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector: {}
  image: quay.io/prometheus/alertmanager:v0.23.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: http-web
  replicas: 1
  retention: 120h
  routePrefix: /
  secrets:
  - slack-pass
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-kube-prometheus-alertmanager
  version: v0.23.0
```

```
$ k get secrets slack-pass
NAME         TYPE     DATA   AGE
slack-pass   Opaque   1      4h16m
```

the value of `alertmanagerSpec.secrets` has been recognized by`Alertmanager` but that secrets has not been mounted under `/etc/alertmanager/secrets/` as described here https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L425

Any idea?

### What's your helm version?

3.7.1

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+rke2r1", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T21:17:43Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+rke2r1", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T21:17:43Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

32.2.0

### Enter the command that you execute and failing/misfunctioning.

/

**Comment by manuelottlik** [comment]
I got the same issue, anyone got ideas?

**Comment by manuelottlik** [comment]
I was able to solve the problem later last night 🎉 
It's actually quite confusing, so I tried to split it in three chapters:

### The problem

I provided the alertmanager config via `alertmanager.config`. This successfully modifies the secret `alertmanager-{nameofyourdeployment}`, but there is actually a second secret that is generated by the prometheus operator, which in my case was called `alertmanager-{nameofyourdeployment}-generated`. From what I could get from the documentation of the prometheus operator and looking in their source code, this is a generated config file that would collect all the `AlertmanagerConfig` CRDs and merge them into one file that is then injected into the alertmanager pods as a volume. **However** it does not include the secret I mentioned earlier.

### The solution

To fix this, I set `alertmanager.alertmanagerSpec.configSecret` to `alertmanager-{nameofyourdeployment}`. Beware though: if you do this, all the fancy CRD merging probably won't work anymore.

### Additional caveats

I found out that the default value for `alertmanager.config` actually contains values that the prometheus operator marks as invalid, because
* `alertmanager.config.route.receiver` is `null` or
* `alertmanager.config.route.routes[0].receiver` is `null` or
* `alertmanager.config.receivers[].name` is `null`

So if the config you set under `alertmanager.config` does not overwrite all of these values and something is not working as expected, take a look in the logs of the prometheus operator container.

### The takeways

I feel like this is a bug. The `alertmanager.config` should definitely make into the secret that gets injected into the pods, otherwise its quite useless to define it in the `values.yaml`. If it's intended behaviour, I feel like this needs more documentation to explain, how this configuration is supposed to be used.

@bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro What is your opinion on this? Are we just doing something completly wrong?

**Comment by ofirshtrull** [comment]
> I was able to solve the problem later last night 🎉 It's actually quite confusing, so I tried to split it in three sections:
> 
> ### The problem
> I provided the alertmanager config via `alertmanager.config`. This successfully modifies the secret `alertmanager-{nameofyourdeployment}`, but there is actually a second secret that is generated by the prometheus operator, which in my case was called `alertmanager-{nameofyourdeployment}-generated`. From what I could get from the documentation of the prometheus operator and looking in their source code, this is a generated config file that would collect all the `AlertmanagerConfig` CRDs and merge them into one file that is then injected into the alertmanager pods as a volume. **However** it does not include the secret I mentioned earlier.
> 
> ### The solution
> To fix this, I set `alertmanager.alertmanagerSpec.configSecret` to `alertmanager-{nameofyourdeployment}`. Beware though: if you do this, all the fancy CRD merging probably won't work anymore because the `alertmanager-{nameofyourdeployment}-generated` secret just gets ignored.
> 
> ### Additional caveats
> I found out that the default value for `alertmanager.config` actually contains values that the prometheus operator marks as invalid, because
> 
> * `alertmanager.config.route.receiver` is `null` or
> * `alertmanager.config.route.routes[0].receiver` is `null` or
> * `alertmanager.config.receivers[].name` is `null`
> 
> So if the config you set under `alertmanager.config` does not overwrite all of these values and something is not working as expected, take a look in the logs of the prometheus operator container.
> 
> ### The takeways
> I feel like this is a bug. The `alertmanager.config` should definitely make into the secret that gets injected into the pods, otherwise its quite useless to define it in the `values.yaml`. If it's intended behaviour, I feel like this needs more documentation to explain, how this configuration is supposed to be used.
> 
> @bismarck @gianrubio @gkarthiks @scottrigby @Xtigyro What is your opinion on this? Are we just doing something completly wrong?

can you please share an example?

**Comment by Zorba-The-Buddha** [comment]
Per [prometheus slack_config docs](https://prometheus.io/docs/alerting/latest/configuration/#slack_config), `api_url_file` must be set under the `slack_config`.

```bash
receivers:
      - name: "null"
      - name: slack-default
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/alertmanager-slack-webhook/slack_api_url
            channel: "#alerts"
            send_resolved: true
```

There’s also `useExistingSecret` which, when `true`, makes the chart ignore `.Values.alertmanager.config`  and use the Secret you provide instead as a volume mount. 

```bash
alertmanager:
  useExistingSecret: true
  alertmanagerSpec:
    configSecret: alertmanager-custom-config
    secrets:
      - alertmanager-slack-webhook
```

You can then pass the file into `slack_api_url` via a secret that matches the name passed to `alertmanagerSpec.configSecret`.

```bash
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-custom-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    route:
      receiver: slack-default
      group_by: ["alertname", "namespace"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - receiver: "null"
          matchers:
            - alertname = "Watchdog"
    receivers:
      - name: "null"
      - name: slack-default
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/alertmanager-slack-webhook/slack_api_url
            channel: "#alerts"
            send_resolved: true
```

I spent too many hours on this, hopefully this helps others... fyi @ofirshtrull, sorry i'm a year late! happy new year
