### ISSUE TITLE
[kube-prometheus-stack] update default image to v0.41.0

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#24]
Not sure when this should happen, but once the chart is ready for this, we can move to [quay.io/prometheus-operator/prometheus-operator](https://quay.io/repository/prometheus-operator/prometheus-operator?tab=tags).

Related: https://github.com/prometheus-operator/prometheus-operator/issues/3416#issuecomment-678256368

**Comment by monotek** [comment]
With the new dockerhub image retention & pull limits it might by good idea to move all images to quay.io where possible.

Might need a new community repo for the dockerfiles where we have control of them.

**Comment by mattymo** [comment]
Are people working on this? There are new probe related CRDs in v0.41.0 I'm looking forward to.

**Comment by mrueg** [comment]
Here's a PR from @sev3ryn that can be used as a starting point https://github.com/helm/charts/pull/23406

**Comment by perezjasonr** [comment]
in its current state if you try to use a newer image it breaks, i opened an issue:

https://github.com/prometheus-community/helm-charts/issues/123

links to related issues (why it breaks) are in there.

i tried prometheus operator v0.42.0 and v0.41.0 and get that error so not sure if something in the chart is what needs to be updated in order to use the newer images.

**Comment by Nitive** [comment]
Looks like it's done and issue should be closed
