### ISSUE TITLE
[mysql exporter] Find the mysql server instance hostname or IP Address

### ISSUE THREAD

**Issue by sandeepmuthathi** [prometheus-community/helm-charts#2523]
### Is your feature request related to a problem ?

I'm using the helm chart to deploy mysqld_exporter to monitor our mysql DB instances. Is there any metrics that we have to get the server IP address/hostname to identify my DB instances? Or if not, how can we add it?

### Describe the solution you'd like.

I'm using the helm chart to deploy mysqld_exporter to monitor our mysql DB instances. Is there any metrics that we have to get the server IP address/hostname to identify my DB instances? Or if not, how can we add it?

### Describe alternatives you've considered.

I'm using the helm chart to deploy mysqld_exporter to monitor our mysql DB instances. Is there any metrics that we have to get the server IP address/hostname to identify my DB instances? Or if not, how can we add it?

### Additional context.

I'm using the helm chart to deploy mysqld_exporter to monitor our mysql DB instances. Is there any metrics that we have to get the server IP address/hostname to identify my DB instances? Or if not, how can we add it?

**Comment by jasonious** [comment]
I came upon this issue while looking for a solution to something that I believe is similar. We run mysql on a VM, and run this prom-mysql-exporter in our kubernetes cluster. It connects and reports everything fine, but in our dashboards all the data shows up as the mysql-exporter's pod IP instead of the host it's monitoring. 

I think that this can be solved via the relabel section of values.yaml, but I've been unable to get it to work. 

```
  relabelings:
  - action: replace
  sourceLabels:
  - "<path:kv/path/to/secret#host>"
  targetLabel: instance
  ```
  
 Like I said, this isn't currently working, but feels like what we want, and similar to what you are after, @sandeepmuthathi 
 
 Ideally, I'd love a way for this to be dynamic, so I didn't have to hardcode the hostname in the sourceLabels field, and could instead use a variable in the chart itself to rewrite this.
