### ISSUE TITLE
[prometheus-kube-stack] additional***Configs generate 'confg' name in postfix  

### ISSUE THREAD

**Issue by SeongJuMoon** [prometheus-community/helm-charts#2533]
### Describe the bug a clear and concise description of what the bug is.

Hi Prometheus team, 

I have enjoyed prometheus all of features and others!!
And I suddenly figure out some name which was generated by template is looking a little different. 

For instance, 
`config` or `configuration` 
https://github.com/prometheus-community/helm-charts/blob/046897216345b83a5cca148448a9e1f374ab1a17/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L273-L275

`confg`
https://github.com/prometheus-community/helm-charts/blob/046897216345b83a5cca148448a9e1f374ab1a17/charts/kube-prometheus-stack/templates/prometheus/additionalAlertmanagerConfigs.yaml#L5

---
It summarized like below: (6qty)

https://github.com/prometheus-community/helm-charts/blob/88447d1886a982b0e26f047d9973d2f6bad7fe7e/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L268-L270

https://github.com/prometheus-community/helm-charts/blob/88447d1886a982b0e26f047d9973d2f6bad7fe7e/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L292-L294

https://github.com/prometheus-community/helm-charts/blob/cd5c69a2ef0a3d5f3478374ba495d27a57b444d4/charts/kube-prometheus-stack/templates/prometheus/additionalScrapeConfigs.yaml#L5

https://github.com/prometheus-community/helm-charts/blob/1b406181133b5843652ac4685d693edd82600eb6/charts/kube-prometheus-stack/templates/prometheus/additionalAlertRelabelConfigs.yaml#L12

https://github.com/prometheus-community/helm-charts/blob/8a715b642a308553198bc47a38ff80d8d3443bba/charts/kube-prometheus-stack/templates/prometheus/additionalAlertmanagerConfigs.yaml#L12

https://github.com/prometheus-community/helm-charts/blob/1b406181133b5843652ac4685d693edd82600eb6/charts/kube-prometheus-stack/templates/prometheus/additionalAlertRelabelConfigs.yaml#L5

If it doesn't mind for you, would you look into this name correction? 
 

### What's your helm version?

version.BuildInfo{Version:"v3.9.1", GitCommit:"a7c043acb5ff905c261cfdc923a35776ba5e66e4", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

kube-prometheus-stack-39.9.0

### Enter the changed values of values.yaml?

```yaml
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'harbor'
      metrics_path: /metrics
      static_configs:
      - targets:
        - 192.168.1.92:9090
```

### Enter the command that you execute and failing/misfunctioning.

It is not command level issue.

**Comment by SeongJuMoon** [comment]
@andrewgkew @desaintmartin
hi there!
If this needs a typo correction, can I write a PR?

**Comment by dmxlsj** [comment]
+1 to this. 
looks like this `confg` term has been derived from the original coreos/prometheus-operator and somehow has been carried over and survived multiple repo migrations. (https://github.com/helm/charts/pull/6765)
This is more like a conventional question rather than an actual bug, but the word `confg` looks quite non-standard to me  (vs traditional `cfg` or `config`) and I also often get confused if it's a typo or not.

My two cents here is that unless there is a specific reason to keep this word convention, maybe it's better to update it to be more explicit and standard especially when the convention is not really consistent with the prometheus operator manifest?
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

It's just a name key, so the blast radius of the change looks quite minimal to me too.
