### ISSUE TITLE
[kube-prometheus-stack] Depend on new prometheus-operator-crds chart for CRDs

### ISSUE THREAD

**Issue by jcpunk** [prometheus-community/helm-charts#2836]
### Is your feature request related to a problem ?

Reduction of duplication

### Describe the solution you'd like.

The `kube-prometheus-stack` chart depending on the newly created `prometheus-operator-crds` chart for the installation of the CRDs.

### Describe alternatives you've considered.

Living with the duplication

### Additional context.

https://github.com/prometheus-community/helm-charts/pull/2697

**Comment by xiu** [comment]
I tried to do this in #2901, here's my understanding: the problem with this approach is that the CRDs are not in the `crds/` directory anymore. As such, they are treated the same as the other resources by helm which leads to resources being pushed while the CRDs are not yet. This is described [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/).

Having the CRDs in `crds/` makes it so that we can't template them and use custom annotations (as was the motivation in #2697.

**Comment by jcpunk** [comment]
Is annotated CRDs something folks need?

**Comment by xiu** [comment]
It comes handy when using tools like ArgoCD, see the justification in #2697.
