### ISSUE TITLE
[prometheus-operator-crds] CRDs not updated with latest version

### ISSUE THREAD

**Issue by maartengo** [prometheus-community/helm-charts#2921]
### Describe the bug a clear and concise description of what the bug is.

PR https://github.com/prometheus-community/helm-charts/pull/2789 created a new major version for the prometheus chart and updated CRDs. I would have expected the prometheus-operator-crds chart to be updated too, but that was not the case. 

### What's your helm version?

not relevant

### What's your kubectl version?

not relevant

### Which chart?

prometheus-operator-crds

### What's the chart version?

0.1.1

### What happened?

Prometheus chart was updated, but CRD chart was not updated.

### What you expected to happen?

I expect that the CRD chart is updated along with the prometheus chart.

### Enter the command that you execute and failing/misfunctioning.

not applicable

### Anything else we need to know?

Is there an automated process to update the chart, or does someone from the community need to manually update the chart?

Please let me know if this is the correct way/place to ask these questions.

**Comment by monotek** [comment]
Helm does not support crd updates.
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

**Comment by svonliebenstein** [comment]
> Helm does not support crd updates.
> https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

Method 2 on that page exactly is the reason why the separate crd chart was created. As can be seen on the originating PR https://github.com/prometheus-community/helm-charts/pull/2697.

Any change on the CRD's in the kube-prometheus-stack chart, should also be updated in the separate operator crd chart. It seems however, that this is not an automated process.

**Comment by rouke-broersma** [comment]
> these charts have no dependency to each other.

In this repo no, in practical use yes there definitely is a dependency. 

We use the operator crds chart to deploy the crds. We use kube-prometheus-stack with skipCRDs to deploy prometheus etc. The CRDs need to be updated before updating kube-prometheus-stack (as per the upgrade manual) so we need to update prometheus-operator-crds before updating kube-prometheus-stack. Since prometheus-operator-crds is not auto-updated when kube-prometheus-stack CRDs are updated we are blocked until prometheus-operator-crds is updated as well.

It would thus be nice to have prometheus-operator-crds updated with the CRD changes at the same time as kube-prometheus-stack is updated with CRD changes. Consider it a feature request, not sure why the issue is closed immediately.

**Comment by maartengo** [comment]
It seems that https://github.com/prometheus-community/helm-charts/issues/2612 still has a discussion on automating the update process. That answers my question; there is no automated update yet. I suppose that the update process is to run the [update_crds.sh](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-operator-crds/hack/update_crds.sh) script and check to makes sure that the diff is OK. 

My short term problem will be resolved by https://github.com/prometheus-community/helm-charts/pull/2922
