### ISSUE TITLE
[prometheus] Support target-heap-size

### ISSUE THREAD

**Issue by DanielYWoo** [prometheus-community/helm-charts#3162]
### Is your feature request related to a problem ?

I need to specify the heap size limit `storage.local.target-heap-size`

### Describe the solution you'd like.

No solution unless the chart supports it

### Describe alternatives you've considered.

N/A

**Comment by DanielYWoo** [comment]
any ideas? don't close it.

**Comment by zanhsieh** [comment]
I don't think prometheus chart would support this since this flag deprecated since 2.x.x. See:

https://stackoverflow.com/questions/61804774/how-to-change-the-heap-size-in-prometheus

https://github.com/prometheus-community/helm-charts/blob/5550ded396156806bd7c432cc5678195d836f01e/charts/prometheus/Chart.yaml#L3
