### ISSUE TITLE
Specify custom Prometheus alerting rules

### ISSUE THREAD

**Issue by ivasilyev-servicetitan-com** [prometheus-community/helm-charts#329]
**Is your feature request related to a problem? Please describe.**
Hello.

I'm running Prometheus (P) with the help of Prometheus Operator (`P O`) by installing `kube-prometheus-stack` helm chart.
I'm trying to utilize GitOps approach, so configuration of my cluster is described in git (I have 
```
chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
``` 
in my gitops repo).

**Describe the solution you'd like**
My task is to add custom Prometheus alerting rules to my P instance.
And important requirement: I want to keep additional rules specification in the same repository where application code lives (!!!not in gitops repo!!!).
Besides, I want to keep predefined P rules, enriching them with my new custom P rules taken from application code repo.

**Describe alternatives you've considered**
I read [Prometheus Monitoring Mixins](https://docs.google.com/document/d/1A9xvzwqnFVSOZ5fD3blKODXfsat5fg6ZhnKu9LK3lB4/edit#heading=h.gt9r2h2gklj3) and read [Developing Prometheus Rules and Grafana Dashboards](https://github.com/prometheus-operator/kube-prometheus/blob/master/docs/developing-prometheus-rules-and-grafana-dashboards.md) As I understood this approach I could use if I used clear [`kube-prometheus`](https://github.com/prometheus-operator/kube-prometheus) project and ran `kubectl apply` myself, but I'm using GitOps + `kube-prometheus-stack` helm chart, so it looks this approach doesn't work for me.

I read about [additionalPrometheusRulesMap](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusrulespec), and I can add additional rules into my gitOps repo, but I need this specification to live in application code repo, not gitops repo, so this approach doesn't work for me.

**Additional context**
I'd like `P O` to have ability to specify custom path for `rule_files` in prometheus config file, but it [doesn't allow](https://github.com/prometheus-operator/prometheus-operator/blob/005278276da81709de532a397b39ce93170916df/pkg/prometheus/promcfg.go#L212) to do this.

So, does any anyone have similar aims? And what the best way to solve this?

**Comment by LuayGrira** [comment]
Having similar issue.. In my case, I built a custom prometheus docker image based on the the original image and added a custom rule files, however, these rules can not be loaded, as there's no way to specify a custom path for `rule_files` in prometheus config file. (We are using the kube-prometheus-stack helm chart).

** Additional context **:
In our case we want to treat the prometheus rule changes as a service update, so whenever there a rule updates, we will have a new docker image and just update the `prometheusSpec.image` value in the gitops repo, rather than having to update/use the `additionalPrometheusRulesMap` value within the gitops repo, as it will be a giant map and not easy to manage and maintain (in our case we have a lot of rules. 

So having the ability to specify a custom path in prometheus config file will be very usefu.
