### ISSUE TITLE
[alertmanager] Persistent Volume 

### ISSUE THREAD

**Issue by Vandersteen** [prometheus-community/helm-charts#335]
**Which chart**: alertmanager

Is there actually a need for the persistent volume in alertmanager ?
Looking inside the pod, there is a single file (alertmanager.yaml), which i guess is generated from the values.yaml of the chart.
Is there a need for a persistent volume or can this be disabled without issues ?

**Comment by terorie** [comment]
Persistence is useful for Alertmanager but it will work without. Please keep it enabled, I find it useful.

When enabled,
- it remembers active/resolved alerts via [nflog](https://github.com/prometheus/alertmanager/blob/311650658ada0ad906b6a6a77c985b7536a09f14/nflog/nflog.go#L18), so you don't get duplicate Slack notifications etc when restarting without persistence
- it [remembers silences](https://github.com/prometheus/alertmanager/blob/c39b787800547eeab882ef5c91543cb5a3596bae/silence/silence.go#L16)
- and probably a few more things

**Comment by Vandersteen** [comment]
Oh yes of course, the silences and resolves need to be stored somewhere.
Thanks for clearing that up

**Comment by terorie** [comment]
@Vandersteen If your question has been answered, would you mind closing this issue?

**Comment by oalimerko** [comment]
Why alertmanagers can not share volumes?Why we can not use `accessMode ReadWriteMany`?
I am asking because sometimes when i restart the AM which is deployed in AKS,restart get stuck because during restart,k8s will start the new pod in a different node from the currently node where the running pod is assigned,depending on resource utilization on the node.In simple words it means,same PVC is accessed from 2 different pods assigned to different nodes

**Comment by kfox1111** [comment]
Because how ha/clustering works. Its designed to be share nothing for fault tolerance.
