### ISSUE TITLE
[all] Should we do a global breaking change to replace sha with digest

### ISSUE THREAD

**Issue by dotdc** [prometheus-community/helm-charts#3355]
### Is your feature request related to a problem ?

@prometheus-community/helm-charts

Sorry to mention everyone here, but I think this is a repository wide decision.

We recently had two PR to replace the `sha` keyword with `digest` : 

prometheus-node-exporter : https://github.com/prometheus-community/helm-charts/pull/3130 (Merged) 
kube-state-metrics : https://github.com/prometheus-community/helm-charts/pull/3248 (Reviewing)

Reason: 
> digest is more commonly used, and prepare for possible future digest types

While I agree on the idea, I'm a little concerned by the fact that this is a breaking change that could also confuse some users.

Grafana, which is also a subchart of kube-prometheus-stack [still uses sha](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L90), while opentelemetry-collector [uses digest](https://github.com/open-telemetry/opentelemetry-helm-charts/blame/main/charts/opentelemetry-collector/values.yaml#L150).

Do you think we should keep `sha` or replace it with `digest`?

Whatever the decision, I think it should be consistent with all the charts in this repository.

What do you think ?

### Describe the solution you'd like.

I personally have a small preference to keep things as is (keep sha everywhere), but I will stand behind the group decision.

### Describe alternatives you've considered.

Replace `sha` with `digest` in all charts.

**Comment by GMartinez-Sisti** [comment]
I expressed my concerns [here](https://github.com/prometheus-community/helm-charts/pull/3191#issuecomment-1540057849).

While I agree that naming should be proper, it's common to use `sha`, most charts have `sha256` hash as default when `sha` is provided.

As a user, I'm not expecting a breaking change without any major functionality or logic change, otherwise it will be hard to find cycles to update something that stays the same.

**Comment by jkroepke** [comment]
I would personally prefer `digest`, since from technical point of view it's the [digest value](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#digests). At the moment, the sha256 algorithm is the most prominent, but from spec point view, this can be changed to any other algorithm.

Other pages outside helm also using the term digest, for example [DockerHub](https://hub.docker.com/layers/prom/prometheus/latest/images/sha256-093db0a26d456ce7c07b51d0994afc08639195e55fdf117adc67102b7ccb6f17?context=explore).

On top, if I'm do a search for [sha256 in values.yaml across all repositories on GitHub](https://github.com/search?q=sha256+lang%3AYAML+path%3Avalues.yaml&type=code), most of the repositories are using `image.digest` instead `image.sha`.

I would disagree that `sha` is more common. I have the feeling that, it's more an outdated pattern from the early days.

**Comment by zeritti** [comment]
Personally, I've got used to `digest`. It is present as an option or as a subcommand in many various tools like crane, crictl, skopeo and docker and is natural to anybody dealing with OCI container images.  

As mentioned above, the main thing is that there's only `digest` in the OCI image specs and I think following that makes perfect sense.

**Comment by sathieu** [comment]
I'm not against keeping `sha`, but it's usage in prometheus-community Helm charts is sometimes counter-intuitive, because it's actually a digest.

I only see one occurrence still wrongly (IMO) using `sha` as digest:

- [kube-state-metrics](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-state-metrics/templates/_helpers.tpl#L123-L137), and it'll be fixed by https://github.com/prometheus-community/helm-charts/pull/3248 🚧 

In the grafana chart mentioned, the `sha` [is only the `sha256` part of the digest](https://github.com/grafana/helm-charts/blob/856a5b583aed4e508f50969fb3b7873866881d30/charts/grafana/templates/_pod.tpl#L25-L27), i.e. for `grafana/grafana:9.5.1@sha256:00a4d2889c2b32f86c50673b1a82cb5b45349f1c24b0a882d11a53518e2ecae4`, this is `00a4d2889c2b32f86c50673b1a82cb5b45349f1c24b0a882d11a53518e2ecae4`.

This intuitive usage of it is used here, in:

- kube-prometheus-stack:
    -  [alertmanagerSpec](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml#L15-L30) ✅ 
    - [operator job-createSecret](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml#L38-L42) ✅ 
    - [operator job-patchWebhook](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml) ✅ 
    - [operator deployment](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L46-L50) ✅ 
    - [operator deployment configReloader](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L46-L50) ✅ 
    - [operator deployment thanorImage](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L111-L115) ✅ 
    - [prometheus](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L34-L46) ✅ 
    - [thanos ruler](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml#L15-L29) ✅ 
- [prometheus-node-exporter DaemonSet](https://github.com/prometheus-community/helm-charts/blob/40e9c2e6a26e84fb39a769d4bdfe73df77582a1b/charts/prometheus-node-exporter/templates/daemonset.yaml#L195C18-L199) ✅ 

I still prefer `digest` over intuitive usage of `sha` (to be future-proof, when sha256 will be broken ; and because this is more widely used), but the added value is lower.

**Comment by monotek** [comment]
If we start to unifying this we would imho need to unify everything.
This would be very hard and would need some libary chart (like the [bitnami common](https://github.com/bitnami/charts/tree/main/bitnami/common)), which would need to be used in all charts.

Also all chart maintainer have to approve to go that step.
I personly have not time to work on that.

**Comment by dotdc** [comment]
Decided to stick with sha on kube-state-metrics for now.
Closing this issue as it would be hard to unify anytime soon.
