### ISSUE TITLE
[kube-prometheus-stack] CPU Usage chart shows No Data

### ISSUE THREAD

**Issue by fabiocruzcoelho** [prometheus-community/helm-charts#3389]
### Describe the bug a clear and concise description of what the bug is.

I'm using kube-Prometheus-stack to get metrics, but I cannot get pod CPU/memory usage, any result is shown, Has anyone had this problem?

I'm using clusters k8s on EKS e locally with kind v1.26

I remember that it already works in previous versions of the helm chart.

![image](https://github.com/prometheus-community/helm-charts/assets/13903548/1ba08a57-e9cf-4c1b-8a1b-620b38c2e1bf)

when I install via repository https://github.com/prometheus-operator/kube-prometheus it works.

any idea about the problem? help-me!!!
 

### What's your helm version?

v3.11.2

### What's your kubectl version?

v1.26

### Which chart?

prometheus-kube-stack

### What's the chart version?

45.28.0

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack

**Comment by QuentinBisson** [comment]
@fabiocruzcoelho this graph uses kube-state-metrics included in the chart. Is it running in your cluster?

**Comment by fabiocruzcoelho** [comment]
> @fabiocruzcoelho this graph uses kube-state-metrics included in the chart. Is it running in your cluster?

Yes

![image](https://github.com/prometheus-community/helm-charts/assets/13903548/467e9507-90c8-4718-ace2-8bb0ef98ba1d)

**Comment by QuentinBisson** [comment]
Can you use the explore function to see the metrics behind the graph and test it on your prometheus? Is your KSM behing monitored by prometheus?

**Comment by fabiocruzcoelho** [comment]
> 

I didn't understand? I have other dashboard and it's working
![image](https://github.com/prometheus-community/helm-charts/assets/13903548/9437487f-a773-4d80-80ee-e1ef9e8974a2)


only the cpu/mem graphics that come with the kube-prometheus-stack stack don't work the others work, I remember that in other versions of the chart these same graphics worked.

**Comment by QuentinBisson** [comment]
Can you check the queries behind the panels that have no data and query them on prometheus directly to check what is happening?

**Comment by QuentinBisson** [comment]
Hmm the metric starting with cluster:node_cpu makes it a recording rules. Can you check if you have any error in your prometheus-operator logs?

**Comment by zeritti** [comment]
It will also be useful to check the state of the recording, i.e. if it is OK in Prometheus UI Status/Rules. 

This recording is an expression with another recording so that one needs to be checked, too. If they are green and yet produce no matches when queried, you'd need to drill down to the base metrics that make up these recordings - if querying these does not return results, the recordings won't either.

Most commonly, it is a missing label or a different label value that prevents the query to return results assuming Prometheus has the required time series.

`cluster:node_cpu:ratio_rate5m` is defined as 
```
avg by (cluster) 
  (node:node_cpu_utilization:ratio_rate5m)
```
and 

`node:node_cpu_utilization:ratio_rate5m` is defined as 
```
avg by (cluster, node)
  (sum without (mode) 
    (rate(node_cpu_seconds_total{job="node-exporter",mode!="idle",mode!="iowait",mode!="steal"}[5m])))
```
The base metric is now `node_cpu_seconds_total`. I would suggest that you execute a query on this metric and evaluate the results, e.g. `rate(node_cpu_seconds_total[5m])`.

**Comment by fabiocruzcoelho** [comment]
The defaultRules value was like saying in my values.yaml file, after changing it to true it worked successfully. closing the issue.
![image](https://github.com/prometheus-community/helm-charts/assets/13903548/9dafab0a-ff72-439c-9d70-1f53c71d7c24)
