### ISSUE TITLE
Git Repo Admins

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#38]
Per #20 we have `CODEOWNERS` so people who maintain the 17 individual prometheus charts can still do so safely while sharing a common GitHub/helm repo with common CI/CD, related issues where appropriate, etc. This will allow the prometheus community charts to grow with new charts, and new maintainers as needed (existing maintainers of a chart can approve new maintainers, and repo admins can add them to the `CODEOWNERS` file).

Now that the repo has transferred, we are moving users from collaborators to GitHub teams.

This is the team structure:
- `helm-charts`: top level team for all members (`Read` access to this git repo)
    - `helm-charts-admins`: nested team (`Admin` access to this git repo)
    - `helm-charts-maintainers` nester team (`Write` access to this git repo)

Currently @brancz @SuperQ and I are in the `helm-charts-admins` team. It wouldn't make sense for all chart maintainers to also do this (that would remove the `CODEOWNERS` benefit mentioned above). I don't know if there is criteria within the prometheus-community org for who can administer the git repo – I have asked, and we'll update this issue with an answer on that.

In the meantime, and apart from that, would it make sense for chart maintainers to have perhaps 2 repo maintainers, and define the duties for that team (what they are expected to do and what they will not do, like merge PRs for other charts they don't maintain). As well as a process for that (perhaps starting with people who have helped with the repo side of things, and then some kind of rotation process)?

I don't need to continue as an admin on this repo now that it's set up, however I'd be ok with staying on that team if people would like me to continue to help as backup.

Let's discuss this here. This repo is co-owned by the charts maintainers and ultimately governed by the prometheus-community org. Just wanted to start the conversation, but I think it's up to all of you. We can only assign 10 people to an issue, so CCing you all below instead:

CC @brancz @SuperQ 

CC [CODEOWNERS](https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS):
- charts/prometheus/ @gianrubio @zanhsieh @Xtigyro
- charts/prometheus-adapter/ @mattiasgees @steven-sheehy @hectorj2f
- charts/prometheus-blackbox-exporter/ @desaintmartin @gianrubio
- charts/prometheus-cloudwatch-exporter/ @gianrubio @torstenwalter @asherf
- charts/prometheus-consul-exporter @timm088
- charts/prometheus-couchdb-exporter @gkarthiks
- charts/prometheus-mongodb-exporter @steven-sheehy
- charts/prometheus-mysql-exporter @juanchimienti @monotek
- charts/prometheus-nats-exporter @okgolove @caarlos0
- charts/prometheus-node-exporter @gianrubio @vsliouniaev
- charts/prometheus-operator @vsliouniaev @bismarck @gianrubio
- charts/prometheus-postgres-exporter @gianrubio
- charts/prometheus-pushgateway @gianrubio @cstaud
- charts/prometheus-rabbitmq-exporter @juanchimienti
- charts/prometheus-redis-exporter @acondrat
- charts/prometheus-snmp-exporter @miouge1
- charts/prometheus-to-sd @acondrat

**Comment by monotek** [comment]
I guess everyone of the chart maintainers can alos review non app specific stuff such as image ttag updates and so on, so the abiltiy to "merge PRs for other charts they don't maintain" makes sense to me as this would fasten up review processes.

**Comment by torstenwalter** [comment]
I just opened PR #44 which adds CODEOWNERS according to the list above.
@scottrigby I saw that you defined them in #1. This splits that up so that we could merge it independent of that. 

I also adjusted the syntax to `/chart/<name-of-chart> @maintainer`.

It matches any files in the chart directory at the root of the repository and any of its subdirectories.
Without the leading / it would also match directories found somewhere else. It's unlikely that those names would be used, but it does not harm to do it this way.

Also added:

```
## changes to CODEOWNERS should be reviewed by repository admins
/CODEOWNERS @helm-charts-admins
```

The intention is that changes to the CODEOWNERS file also needs to be reviewed by one of the repository admins. One could argue, that it could delay the process of adding maintainers. In case one maintainer of a chart is added to another chart that is true! In case an external person is added that's not really the case as one of the repository administrators would need to grant him/her write permissions to the repository anyhow.

I also added a draft for `PROCESSES.md`, which at the moment just outlines how to add maintainers. We could use that file for further process documentation if needed.

When introducing CODEOWNERS we will have an issue with charts which only have one maintainers. If that maintainer make a change then he is not able to approve it. Repository admins would need to use their "superpower" to override the required review and can merge it. That might be ok for the start, but I would suggest that we try to add at least a second maintainer there.

Affected charts are:

- [ ] charts/prometheus-consul-exporter @timm088
- [ ] charts/prometheus-couchdb-exporter @gkarthiks
- [ ] charts/prometheus-mongodb-exporter @steven-sheehy
- [ ] charts/prometheus-postgres-exporter @gianrubio
- [ ] charts/prometheus-rabbitmq-exporter @Juanchimienti
- [ ] charts/prometheus-redis-exporter @acondrat
- [ ] charts/prometheus-snmp-exporter @Miouge1
- [ ] charts/prometheus-to-sd @acondrat

Would be great if we could fined volunteers here or even better if the chart maintainers could try to motivate people who already contributed to the chart to become maintainer.

**Comment by torstenwalter** [comment]
If you need an a helping hand than I could support as repository admin. From my understanding repository admins should not approve PRs for charts unless they are maintainer of the chart or one of the maintainers of a chart explicitly asks for it.

@scottrigby You did a great job in setting all this up and driving discussions. At least I would appreciate if you could continue helping as admin.

**Comment by scottrigby** [comment]
@torstenwalter I updated your PR title to be just about the PROCESSES documentation (which is great!), because /.github/CODEOWNERS already exists (I added it there in #12, for tidiness).

**Comment by scottrigby** [comment]
@torstenwalter Also agree charts with a single maintainer should ideally have at least two. Hopefully people can work that out in #21. Do you want to move that part of your comment there?

**Comment by torstenwalter** [comment]
> @torstenwalter Also agree charts with a single maintainer should ideally have at least two. Hopefully people can work that out in #21. Do you want to move that part of your comment there?

Just moved it there https://github.com/prometheus-community/helm-charts/issues/21#issuecomment-687666865

**Comment by scottrigby** [comment]
@torstenwalter you’re now a member of the @prometheus-community/helm-charts-admins team. So we have at least a few people to help with this side of things for now.

Let's all make sure processes like team membership (criteria, responsibilities and limitations) explicit in the PROCESSES doc being added in #44.

Once that's merged, we can probably close this issue and make further amendments to the PROCESSES doc in follow-up PRs, and discuss other questions or ideas that come up in new issues.

**Comment by timm088** [comment]
@scottrigby @torstenwalter not entirely sure whats being requested?
Haven't modified the consul-exporter chart in a while, but would be happy to assist where it makes sense.

Is the request here to try to gather support from existing contributors on that chart, to become CODEOWNERs?

Or , nothing to do and just an FYI?

**Comment by scottrigby** [comment]
Hey @timm088 👋 thanks for asking! This issue needs clarification and closure.

There was a little confusion above - the CODEOWNERS file already exists, and added your ownership for the consul exporter chart: https://github.com/prometheus-community/helm-charts/blob/c30ca3376262543faf8ba878c0c46d16ab8af3c1/.github/CODEOWNERS#L13

That means you should already get a review request whenever someone opens a PR with any changes on it 👍 there should be nothing for there to do there.

@torstenwalter 's suggestion above was for all the chats in this repo to have at least two maintainers (there's another issue for that: #21). @gkarthiks made a PR to add him as a co-maintainer of your chart in #50. It's up to you though as a (currently only) maintainer of that chart to approve his request in that PR or not. 

This issue was me asking all the current prom chart maintainers opinion on how repo administration should work (if people would like to rotate, vote on people who have shown they want to and are able to do it, etc). @torstenwalter volunteered earlier, and we worked together to set up a few other community chart repos (grafana and jenkins), so I added him as a repo admin. We now have a PROCESSES doc file for this repo, so you can all make PRs against that and discuss any additional process ideas and needs you have there. 

For now I think this issue is done because it's not just me as admin anymore, so I'm going to close it. Let's all continue in the other issues 🙂

**Comment by timm088** [comment]
Cool, thanks for the explanation @scottrigby , all makes sense now
