### ISSUE TITLE
kube-prometheus-stack's alertmanager CRDs are empty but pod config was populated

### ISSUE THREAD

**Issue by rafaelvanoni** [prometheus-community/helm-charts#3957]
I'm trying to enable alertmanager in my cluster and have a config that passes `amtool config-check` and doesn't generate any errors when applied (nothing in the operator pod's log). The config is in the main kube-prometheus-stack chart:
```
  kube-prometheus-stack:
  [...]
  alertmanager:
    enabled: true
    alertManagerSpec:
      secrets: ['pagerduty']
    config:
      global:
      [...]
```
I exec'ed into the alertmanager pod and see my config got there correctly. But the alertmanager CRDs don't seem to have changed at all:
```
$ kubectl -n mynamespace get alertmanagerconfigs.monitoring.coreos.com -o yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
```
Some things to note:
- both prometheus and alertmanager are in the same namespace
- I haven't created any actual alerts yet
- my root level receiver doesn't do anything, I have child receivers configured tho

Any pointers would be much appreciated.

*I originally reported this in the prometheus-operator project
https://github.com/prometheus-operator/prometheus-operator/issues/6048

### What's your helm version?

version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}

### What's your kubectl version?

Client Version: v1.28.3 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.27.6-eks-f8587cb

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.27.1

### What happened?

Add a valid `alertmanager` config in the `kube-prometheus-stack` chart, this resulted in an alertmanager pod being created and the configuration populated in the pod's config file.

### What you expected to happen?

In addition to the alertmanager pod being created with the specified config, I expected the `alertmanager` and `alertmanagerconfig` CRDs to be populated. They didn't change at all (the `alertmanager` CRD stayed at a default and `alertmanagerconfig` remained empty).

### How to reproduce it?

Add a valid `alertmanager` config in the `kube-prometheus-stack` chart and apply it.

### Enter the command that you execute and failing/misfunctioning.

We're using terragrunt to apply this chart.

**Comment by zeritti** [comment]
> In addition to the alertmanager pod being created with the specified config, I expected the alertmanager and alertmanagerconfig CRDs to be populated. They didn't change at all (the alertmanager CRD stayed at a default and alertmanagerconfig remained empty).

If `alertmanager.enabled=true`, the chart will create an `alertmanager` CR and Prometheus Operator will then launch the corresponding resources provided all sanity checks have passed. As your alertmanager is running, this was indeed completed successfully.

If you use `alertmanager.config` (or, alternatively, `alertmanager.stringConfig`), the chart will create a secret with a specific name and key `alertmanager.yaml` that Prometheus Operator will pick up and make available in the container as alertmanager's configuration file (more [info](https://prometheus-operator.dev/docs/user-guides/alerting/#managing-alertmanager-configuration)). You can create this secret yourself and refer to it by means of `alertmanager.alertmanagerSpec.useExistingSecret`.

The chart does not create an `alertmanagerconfig` CR at all. What you see in the output is an empty list (`kind: List`) which has no relation to `alertmanagerconfig` resources, apart from reporting there is none (this output is caused by the yaml option, you'd get _No resources found..._ without it in the given namespace). The `alertmanager` CR itself does not change when the config changes since the config is not part of it. On the other hand, changing properties in `alertmanager.alertmanagerSpec` would make changes in the resource.

**Comment by rafaelvanoni** [comment]
Cool, thanks for the thorough reply.

**Comment by tewfik-ghariani** [comment]
Hi [zeritti](https://github.com/zeritti), just one follow up question, how is it expected to create the alertmanagerconfig CR by the users?

Should that be done manually by creating full manifests? Or is there a separate chart with ready-to-use templates for all custom resources?
