### ISSUE TITLE
[kube-prometheus-stack] Installation problems

### ISSUE THREAD

**Issue by darvik-ai** [prometheus-community/helm-charts#4250]
Hello everyone,  
we are facting issue on install prometheus & grafana using helm 
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Alertmanager.spec.securityContext): unknown field "seccompProfile" in com.coreos.monitoring.v1.Alertmanager.spec.securityContext

we are using  below chart.
Chart Name : prometheus-community/kube-prometheus-stack  
CHART VERSION : 49.2.0  
APP VERSION: v0.67.1

Our kuberntes version :  v1.23.10

anyone help us?

**Comment by zeritti** [comment]
It appears as if Prometheus operator CRDs were already installed, although very much outdated - `Alertmanager.spec.securityContext.seccompProfile` has been supported since release 0.52.

Please, see, whether this is the case. If it is, you can either delete the CRDs if conditions allow prior to installing the chart or [upgrade](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-48x-to-49x) them separately before installing the chart.

**Comment by darvik-ai** [comment]
Thanks
