### ISSUE TITLE
What happens when I set the replica to 2?

### ISSUE THREAD

**Issue by lifeofmoo** [prometheus-community/helm-charts#4461]
Hello,

We've deployed kube-prometheus-stack chart and it's running great!

The main prom pod is a count of one (replicas: 1)

We've set the replica count to 2 in the helm chart. However we're unsure if this will cause adverse behavior. 

What happens under the hood if we leave this at replica=2? Are we getting any HA benefits by doing so?

**Comment by jkroepke** [comment]
If you run Prometheus with replica 2, both prometheus will scrape and save the data. 

Since prometheus doesn't have a cluster capabilities, both instance runs on they own and does not know from each other.

For a Prometheus HA solution, you many need specialized solution like Thanos, Cortex or Mimir

**Comment by kfox1111** [comment]
Its part of prometheus's ha design to run two prometheus instances, and an alertmanager cluster, and alertmanager will squash duplicate notifications when all is working properly.
