### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Annegies** [prometheus-community/helm-charts#509]
Hi,

Right now it's very hard to check what has changed in the charts. 
Would it be possible to create a changelog or another way for me to verify what has changed in new versions

**Comment by monotek** [comment]
You can check the changes via the history of the chart.yaml which references the pull requests.

**Comment by scottrigby** [comment]
Yep, this is why we carried over git history when migrating charts from `stable`. See https://github.com/prometheus-community/community/issues/28

Some chart maintainers do write manually maintain a changelog, however most find it tedious, redundant (because of what @monotek said above), and the problems that come with duplication (like missing things, or getting out of sync).

One practice that maintainers in this and a number of other chart repos follow is to 1. adhere to semver, and 2. keep is to maintain an "upgrading" section of the README, which lists breaking changes for each MAJOR version. See https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#versioning for reference.

**Comment by brujoand** [comment]
I came to create this exact issue, so I'll leave my comment here instead of creating a new one. I do agree and understand that keeping a complete up to date changelog for all minor versions is tedious, and to be honest not really that relevant. 

But when this chart bumps a major version it should mean that something is no longer backwards compatible. In other words, I as a user need to make sure I take the new changes into account and upgrade with care. 

In these cases I would really appreciate a note on the release as to why there was a bump in major version. But looking at the diff between 12.12.2 --> 13.0.0 there doesn't seem to be any major or breaking changes.
[ref](https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-12.12.2...kube-prometheus-stack-13.0.0) and the Release of 13.0.0 doesn't mention anything either.

Am I missing something here?

**Comment by monotek** [comment]
Such changes should be always described in the upgrading section of the readme of the chart.

**Comment by brujoand** [comment]
I might be blind, but could you past a link to this upgrading section?

**Comment by longwuyuan** [comment]
> I might be blind, but could you past a link to this upgrading section?

https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-chart

**Comment by brujoand** [comment]
doh, that actually makes perfect sense. Thanks.

**Comment by bergerx** [comment]
Wouldn't it make sense to place a link to the corresponding chart's upgrading section in its release notes?

To be more precise, place links to upgrade sections in here:
https://github.com/prometheus-community/helm-charts/releases
![image](https://user-images.githubusercontent.com/45531/117902760-13c6da80-b2c6-11eb-8063-9ff1ff996e72.png)
