### ISSUE TITLE
[kube-prometheus-stack] Is possible to set the --storage.tsdb.path value via values.yaml?

### ISSUE THREAD

**Issue by aalcaraz97** [prometheus-community/helm-charts#825]
**Is your feature request related to a problem? Please describe.**
Is it possible to change the --storage.tsdb.path value in the prometheusSpec section in the values.yaml? 

I have checked all the possible fields of the Prometheus CRD, and I'm seeing fields to configure the retention period, retention size, enable the Admin API, etc. but I do not see a field to specify the --storage.tsdb.path flag, which in the Prometheus deployment is always "/prometheus".

If I describe the Prometheus pod after installing the Helm Chart, the flag value is always "/prometheus":
```
$ kubectl describe pod -n <prometheus-namespace> prometheus-prometheus-0
Name:         prometheus-prometheus-0
[...]
Containers:
  prometheus:
    [...]
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=14d
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.enable-admin-api
      --web.route-prefix=/
```

I'm using the following versions:
- kube-prometheus-stack v14.3.0
- Kubernetes v1.20.4

**Describe the solution you'd like**
A new field in the prometheusSpec section on the values.yaml to specify the --storage.tsdb.path flag value

**Describe alternatives you've considered**
I'm thinking of an alternative, which is basically patching the Prometheus pod associated with the Prometheus StatefulSet, and modifying directly the "prometheus" container args to update the --storage.tsdb.path flag value, but not sure if it is the best idea and it will be scalable if I add more Prometheus replicas on the future in my cluster.

**Additional context**
-

**Comment by rmorilha** [comment]
Any successful implementation for this ?

With the support for Prometheus Agent in the values file (prometheusSpec.enableFeatures.agent), some configurations must be disabled.

More specifically:
- `--storage.tsdb.retention.time`   --> Able to disable this in the kube-prometheus-stack values.yaml param `prometheusSpec.retention`
- `--storage.tsdb.wal-compression`   --> Able to disable this in the kube-prometheus-stack values.yaml param `prometheusSpec.walCompression`
- `--storage.tsdb.path`  --> UNABLE to disable/configure this through kube-prometheus-stack values.yaml
   - Already tried to remove the storage spec itself.
   - Already tried to remove manually from statefulset (operator adjusts it back)

**Current kube-prometheus-stack chart version**: 40.1.2
**Current prometheus version**:  v2.38.0
**Current prometheus operator version**: v0.59.1

**Below follows the log from prometheus pod:**
```bash
ts=2022-09-29T17:11:14.618Z caller=main.go:187 level=info msg="Experimental agent mode enabled."
The following flag(s) can not be used in agent mode: ["--storage.tsdb.retention.time" "--storage.tsdb.path" "--storage.tsdb.wal-compression"]
```

As far as I could see in the code, the Prometheus chart templates has openness for the addition of a values parameter to support this disablement/configuration path...more specifically in the files:
- sts.yaml
   - Under filepath `prometheus/templates/server/sts.yaml`
   - On lines 107 -> 110
- deploy.yaml
   - Under filepath `prometheus/templates/server/deploy.yaml`
   - On lines 103 -> 107

Below follows the code of the files aforementioned:

**sts.yaml:**
```yaml
          {{- if .Values.server.storagePath }}
            - --storage.tsdb.path={{ .Values.server.storagePath }}
          {{- else }}
            - --storage.tsdb.path={{ .Values.server.persistentVolume.mountPath }}
          {{- end }}
```

**deploy.yaml:**
```yaml
            {{- if .Values.server.storagePath }}
            - --storage.tsdb.path={{ .Values.server.storagePath }}
            {{- else }}
            - --storage.tsdb.path={{ .Values.server.persistentVolume.mountPath }}
            {{- end }}
```

Currently, these files only contains the enforcement of the `--storage.tsdb.path` argument, either through `server.storagePath` or  `server.persistentVolume.mountPath`, but no option to **not** have it (again, due to Prometheus agent support feature enabled since 2.32 version of prometheus).

I have never contributed in an open-source project before and I also have zero experience with operators, specially Prometheus.
Can someone that is more versed on the prometheus open-source repository and code, implement the disablement of the above-mentioned `storage.tsdb.path` and allow it to be configurable all the way until kube-prometheus-stack values file ?
